version: '3'
services:
  speedtest:
    build: 
      context: ./golang
    ports: 
      - "8081:8081"
    networks:
      - theNet
  
  Prometheus:
    image: prom/prometheus:v2.51.0-dedupelabels
    hostname: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - theNet

  Grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - theNet

networks:
  theNet: {}

volumes:
  prometheus_data: {}
  grafana_data: {}
