version: '3'
services:
  speedtest:
    build: 
      context: ./golang
    ports: 
      - "8081:8081"
    networks:
      - theNet
  
  Prometheus:
    image: prom/prometheus:v2.51.0-dedupelabels
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - theNet

  Grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - theNet

networks:
  theNet: {}

volumes:
  prometheus_data: {}
  grafana_data: {}
