version: '3'
services:
  speedtest:
    build:
      context: .
    ports: 
      - "8081:8081"
    networks:
      - theNet
  
  Prometheus:
    image: prom/prometheus:v2.50.0-rc.0
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    networks:
      - theNet

  Grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - theNet

networks:
  theNet: {}

volumes:
  prometheus_data: {}
  grafana_data: {}